spring:
  application:
    name: comments-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comments_service_db
    username: dev
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    search-path: classpath:/liquibase/
    duplicate-file-mode: WARN
    enabled: true
    default-schema: app

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
