server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: dev
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog-master.xml

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000        # 15 минут (в миллисекундах)
  refresh-expiration: 1209600000   # 14 дней

logging:
  level:
    root: INFO
