spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000
  issuer: "auth-service"
