-- ALTER USER dev CREATEROLE CREATEDB;
GRANT CREATE ON DATABASE comments_service_db TO dev;

CREATE SCHEMA IF NOT EXISTS app;
GRANT ALL PRIVILEGES ON SCHEMA app TO dev;

CREATE SCHEMA IF NOT EXISTS service;
GRANT ALL PRIVILEGES ON SCHEMA service TO dev;