name: Dev example CI

on:
  pull_request:
    branches: [dev]
    paths:
      - 'backend/notification-service/**'
      - '!backend/pom.xml'

jobs:
  detect-changed-modules:
      runs-on: ubuntu-latest
      outputs:
        modules: ${{ steps.get-modules.outputs.modules }}
      steps:
        - uses: actions/checkout@v4
        
        - name: Get changed modules
          id: get-modules
          run: |
            # Получаем список измененных папок модулей
            CHANGED_MODULES=$(git diff --name-only origin/dev...HEAD | grep -o 'backend/[^/]*' | sort | uniq | sed 's|backend/||')
            echo "Changed modules: $CHANGED_MODULES"
            echo "modules=$CHANGED_MODULES" >> $GITHUB_OUTPUT
          
  build-and-test:
    needs: detect-changed-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-changed-modules.outputs.modules) }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test ${{ matrix.module }}
        run: |
          cd backend/${{ matrix.module }}
          mvn clean test

      - name: Checkstyle
        run: |
          cd backend/${{ matrix.module }}
          mvn checkstyle:check
