name: Service Test CI

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      need_db:
        default: false
        type: boolean
      db_password:
        required: false
        type: string


jobs:
  service-test:
    runs-on: ubuntu-latest
    env:
      DB_MODULE: ${{ replace(inputs.module, '-', '_') }}
      DB_NAME: ${{ env.DB_MODULE }}_db  #
      DB_USER: dev
      DB_PASSWORD: ${{ inputs.db_password || '' }}
    services:
      postgres:
        if: ${{ inputs.need_db }}
        image: postgres:17-alpine
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}_db
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: ${{ inputs.db_password }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - run: |
          cd backend/${{ inputs.module }}
          mvn clean test
          



