name: Dev-ci

on:
  pull_request:
    branches: [dev]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build and Test
        run: |
          cd backend/example-service
          mvn clean test
      - name: Checkstyle
        run: mvn checkstyle:check
